name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Install Dependencies
        run: |
          pod install --repo-update
        shell: bash
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
