name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Install Dependencies
        run: |
          pod install --repo-update
        shell: bash
      - uses: ty0x2333/cocoapods-action@master
        with:
          additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'
          additional_lint_params: --private
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
